<section style="padding:40px 0px;" id="TermsAndConditions-section">
	<div class="container">
		<div class="row">
			<div class="col-lg-2 col-md-2 col-sm-12">&nbsp;</div>
			<div class="col-lg-8 col-md-8 col-sm-12 card" style="border:px solid black;max-width:100%;border-radius: 0px;text-align: left;padding:10px;">
				<h1 style="text-align: center;">TERMS AND CONDITIONS</h1><hr>
				<p>PLEASE READ THE FOLLOWING TERMS AND CONDITIONS RELATING TO YOUR USE OF THIS SITE AND THE PRODUCTS AND SERVICES PROVIDED HEREUNDER CAREFULLY.</p><br>
				<p>By i) using this site, ii) purchasing any products or services through link from this site. or iii) utilizing any of the services from us through this site, you are deemed to have agreed to these Terms and Conditions. We reserve the right to modify them at any time. You should check these Terms and Conditions periodically for changes. By using this site after we post any changes to these Terms and Conditions, you agree to accept those changes, whether or not you have reviewed them. With regard to products and services purchased or utilized from us, the version of these Terms and Conditions that were posted at the time of purchase or utilization apply. If at any time you choose not to accept these Terms and Conditions of use, do not use this site.</p><br>

				<h4>General Terms and Conditions</h4>
				<h4>a) Scope of Terms and Conditions</h4>
				<p>These Terms and Conditions apply to your use of all of the website at this domain, as well as any of its sub-domains and related domains, as well as to services utilized from the Site. Unless stated otherwise, all references to the Site in these Terms and Conditions include this Site. These Terms and Conditions do not apply to your use of unaffiliated sites to which the Site only links.</p><br>

				<h4>b) Restrictions on Use</h4>
				<p>The contents of this site are protected by copyright and trademark laws, and are the property of their owners. Unless we say otherwise, you may access the materials located within the Site only for your personal use. This means you may download one copy of posted materials on a single computer for personal, noncommercial home use only, so long as you neither change nor delete any author attribution, trademark, legend or copyright notice. When you download copyrighted material you do not obtain any ownership rights in that material.</p><br>
				<p>You may not modify, copy, publish, display, transmit, adapt or in any way exploit the content of the Site. Only if you obtain prior written consent from us and from all other entities with an interest in the relevant intellectual property may you publish, display or commercially exploit any material from the Site.</p><br>
				<p>You must abide by all additional copyright notices or other restrictions contained in any of the Site.</p>
				<p>You agree not to do any of the following while using the Site:<br /></p> <ul> <li>harass, stalk or otherwise abuse another user;</li> <li>transmit or otherwise make available any content that is false, harmful, threatening, abusive, tortious, defamatory, libelous, disparaging (including disparaging of the Site), vulgar, obscene, pornographic or that promotes violence, racial hatred, terrorism or illegal acts, or is otherwise objectionable (as determined by us in our sole discretion);</li> <li>transmit or otherwise make available any content that is unlawful or infringes, violates or misappropriates any patent, trademark, trade identity right, trade secret, publicity right, privacy right, copyright or any other intellectual property or any other rights of any third party;</li> <li>upload or transmit viruses, Trojan horses or other harmful, disruptive or destructive files or post material that interferes with any third party’s uninterrupted use and enjoyment of the Site.</li> <li>impersonate any person or entity, or otherwise disguise the origin of any content transmitted through the Site or to us, including forging any TCP/IP packet header or any part of the header information in any transmission to the Site for any reason;</li> <li>transmit or otherwise make available through the Site any personal advertising, junk mail, spam, chain letters, pyramid schemes or offer for sale of any products or services, except in areas specifically designated for such purposes; or</li> <li>violate any applicable local, state, federal or international law, rule or regulation.</li> </ul>

				<h4>c) Links</h4> 
				<p>These Terms and Conditions apply only to this Site, and not to the sites of any other companies or organizations, including those to which this Site may link. We are not responsible for the availability of any other site to which this Site links. We do not endorse or take responsibility for the contents, advertising, products or other materials made available through any other site. Under no circumstances will we be held responsible or liable, directly or indirectly, for any loss or damage that is caused or alleged to have been caused to you in connection with your use of, or reliance on, any content, goods or services available on any other site. You should direct any concerns to that site administrator or webmaster.</p> <p>Other sites may link to this Site only through a plain-text link or provided graphics link. Permission must be granted by us for any other type of link to the Site. To seek our permission, you may send an email to support mentioned below. We reserve the right, however, to rescind any permission granted by us to link through a plain-text link or any other type of link, and to require termination of any such link this Site, at our discretion at any time.</p> <p>THE SERVICES, PRODUCTS AND MATERIALS ON OR FROM THIS SITE ARE PROVIDED “AS IS” AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DISCLAIM ALL WARRANTIES TO THE MAXIMUM EXTENT OF THE LAW, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.</p> <p>NEITHER WE NOR ANY OF OUR RESPECTIVE LICENSORS OR SUPPLIERS WARRANT THAT ANY FUNCTIONS CONTAINED IN THE SITE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SITE OR THE SERVER THAT MAKES THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p> <p>NEITHER WE NOR ANY OF OUR RESPECTIVE LICENSORS OR SUPPLIERS WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE SERVICES, PRODUCTS OR MATERIALS IN THIS SITE IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. YOU (AND NOT WE OR ANY OF OUR RESPECTIVE LICENSORS OR SUPPLIERS) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION TO YOUR SYSTEM.</p><p>We do not endorse, warrant or guarantee any products or services offered on the Site. We are not a party to, and do not monitor, any transaction between users and third party providers of products or services.</p><br>

				<h4>CONTACTING US</h4>
				<p>You can reach our support by emailing us at support mentioned below.</p>
			</div>
		</div>
	</div>
</section>
<script type="text/javascript">
	document.getElementById('TermsAndConditions-section').style.minHeight=screen.height+"px";
</script>